"""TEO Phase 5 reference orchestration engine."""

from .anthropic_adapter import AnthropicMessagesAdapter, execute_anthropic_canary_once
from .anthropic_verifier import AnthropicLiveVerifier
from .benchmark_conclusion import (
    BenchmarkConclusionHandoffRecord,
    BenchmarkConclusionRecord,
    BenchmarkConclusionVerificationRecord,
    advance_benchmark_conclusion,
    build_benchmark_conclusion,
    build_benchmark_conclusion_verification,
)
from .benchmark_lab import (
    BenchmarkExperimentManifest,
    BenchmarkExperimentReport,
    BenchmarkFixtureRecord,
    JsonlBenchmarkReportSink,
    evaluate_benchmark,
    load_benchmark_fixtures,
    load_route_outcomes,
)
from .benchmark_replay import (
    BenchmarkReplayPlan,
    ControlledReplayExecution,
    evaluate_controlled_replay,
    run_controlled_replay,
)
from .benchmark_verification import (
    BenchmarkVerifierObservation,
    BenchmarkVerifierPanelPlan,
    JsonlBenchmarkVerifierObservationSink,
    attach_verifier_disagreement,
    execute_benchmark_verifier_panel,
)
from .cost_attribution import (
    BillingSurfaceContext,
    JsonlRouteCostAttributionSink,
    PricingCatalog,
    PricingEvidenceRecord,
    RouteCostAttributionRecord,
    VerificationUsageEvidence,
    attribute_route_cost,
    load_pricing_evidence,
)
from .engine import OrchestrationEngine as BaseOrchestrationEngine
from .google_adapter import GeminiInteractionsAdapter, execute_gemini_canary_once
from .google_verifier import GoogleLiveVerifier
from .live_scope_candidate import (
    LiveScopeCandidateEvaluation,
    LiveScopeCandidateGate,
    LiveScopeExpansionPolicy,
    evaluate_live_scope_candidate,
)
from .live_scope_replay import (
    LiveScopeReplayExecution,
    LiveScopeReplayPlan,
    LiveScopeReplayRecord,
    run_staged_documentation_replay,
)
from .openai_adapter import OpenAIResponsesAdapter, execute_openai_canary_once
from .openai_verifier import OpenAILiveVerifier
from .provider_adapter import (
    ProviderAdapter,
    ProviderAdapterContractError,
    ProviderExecutionRequest,
    ProviderExecutionResponse,
    ProviderFailure,
    ProviderUsage,
    ReasoningEffort,
    execute_provider_once,
)
from .provider_connection import (
    HeaderProviderConnection,
    ProviderConnection,
    ProviderConnectionError,
    ProviderConnectionRequest,
    ProviderConnectionResponse,
)
from .qualified_human_approval import (
    JsonlQualifiedHumanApprovalLedger,
    QualifiedHumanApprovalDispositionRecord,
    QualifiedHumanApprovalRequestRecord,
    QualifiedHumanAuthorityGrantRecord,
    QualifiedHumanFinalizationRecord,
    build_qualified_human_approval_disposition,
    build_qualified_human_approval_request,
    build_qualified_human_authority_grant,
    evaluate_qualified_human_finalization,
)
from .route_outcome import (
    JsonlRouteOutcomeSink,
    RouteOutcomeRecord,
    RouteOutcomeVersionContext,
    build_abandoned_route_outcome,
    build_guarded_canary_route_outcome,
)
from .runtime_canary import CanaryRuntimeOutcome, execute_guarded_canary
from .runtime_circuit_breaker import (
    CircuitStateStore,
    InMemoryCircuitStateStore,
    JsonFileCircuitStateStore,
    ProviderCircuitBreaker,
    ProviderCircuitPolicy,
    ProviderCircuitRecord,
)
from .runtime_retry import RetryExecution, RetryPolicy, execute_with_transient_retry
from .runtime_telemetry import (
    InMemoryRuntimeTelemetrySink,
    JsonlRuntimeTelemetrySink,
    RuntimeTelemetryEvent,
    RuntimeTelemetryPolicy,
    RuntimeTelemetrySink,
)
from .runtime_verification import (
    LiveVerificationExecution,
    active_execution_from_outcome,
    execute_live_verification,
    execute_live_verification_with_evidence,
    verify_guarded_canary_outcome,
    verify_guarded_canary_outcome_with_evidence,
)
from .schemas import DispatchRecord, FinalOutcome, TaskRequest, VerificationResult
from .shadow_evaluation import (
    JsonlShadowRecommendationSink,
    ShadowEvaluationInputRecord,
    ShadowRecommendationHandoffRecord,
    ShadowRecommendationRecord,
    ShadowRecommendationVerificationRecord,
    advance_shadow_recommendation,
    build_shadow_evaluation_input,
    build_shadow_recommendation_verification,
    evaluate_shadow_routes,
)
from .specialist_routing import SpecialistRoutingEngine
from .verification_adapter import (
    LiveVerificationDecision,
    LiveVerificationError,
    LiveVerificationRequest,
    LiveVerificationResponse,
)
from .verification_policy import LiveVerificationPolicy

OrchestrationEngine = SpecialistRoutingEngine

__all__ = [
    "AnthropicLiveVerifier",
    "AnthropicMessagesAdapter",
    "BaseOrchestrationEngine",
    "BenchmarkConclusionHandoffRecord",
    "BenchmarkConclusionRecord",
    "BenchmarkConclusionVerificationRecord",
    "BenchmarkExperimentManifest",
    "BenchmarkExperimentReport",
    "BenchmarkFixtureRecord",
    "BenchmarkReplayPlan",
    "BenchmarkVerifierObservation",
    "BenchmarkVerifierPanelPlan",
    "BillingSurfaceContext",
    "CanaryRuntimeOutcome",
    "CircuitStateStore",
    "ControlledReplayExecution",
    "DispatchRecord",
    "FinalOutcome",
    "GeminiInteractionsAdapter",
    "GoogleLiveVerifier",
    "HeaderProviderConnection",
    "InMemoryCircuitStateStore",
    "InMemoryRuntimeTelemetrySink",
    "JsonFileCircuitStateStore",
    "JsonlBenchmarkReportSink",
    "JsonlBenchmarkVerifierObservationSink",
    "JsonlQualifiedHumanApprovalLedger",
    "JsonlRouteCostAttributionSink",
    "JsonlRouteOutcomeSink",
    "JsonlRuntimeTelemetrySink",
    "JsonlShadowRecommendationSink",
    "LiveScopeCandidateEvaluation",
    "LiveScopeCandidateGate",
    "LiveScopeExpansionPolicy",
    "LiveScopeReplayExecution",
    "LiveScopeReplayPlan",
    "LiveScopeReplayRecord",
    "LiveVerificationDecision",
    "LiveVerificationError",
    "LiveVerificationExecution",
    "LiveVerificationPolicy",
    "LiveVerificationRequest",
    "LiveVerificationResponse",
    "OpenAILiveVerifier",
    "OpenAIResponsesAdapter",
    "OrchestrationEngine",
    "PricingCatalog",
    "PricingEvidenceRecord",
    "ProviderAdapter",
    "ProviderAdapterContractError",
    "ProviderCircuitBreaker",
    "ProviderCircuitPolicy",
    "ProviderCircuitRecord",
    "ProviderConnection",
    "ProviderConnectionError",
    "ProviderConnectionRequest",
    "ProviderConnectionResponse",
    "ProviderExecutionRequest",
    "ProviderExecutionResponse",
    "ProviderFailure",
    "ProviderUsage",
    "QualifiedHumanApprovalDispositionRecord",
    "QualifiedHumanApprovalRequestRecord",
    "QualifiedHumanAuthorityGrantRecord",
    "QualifiedHumanFinalizationRecord",
    "ReasoningEffort",
    "RetryExecution",
    "RetryPolicy",
    "RouteCostAttributionRecord",
    "RouteOutcomeRecord",
    "RouteOutcomeVersionContext",
    "RuntimeTelemetryEvent",
    "RuntimeTelemetryPolicy",
    "RuntimeTelemetrySink",
    "ShadowEvaluationInputRecord",
    "ShadowRecommendationHandoffRecord",
    "ShadowRecommendationRecord",
    "ShadowRecommendationVerificationRecord",
    "SpecialistRoutingEngine",
    "TaskRequest",
    "VerificationResult",
    "VerificationUsageEvidence",
    "active_execution_from_outcome",
    "advance_benchmark_conclusion",
    "advance_shadow_recommendation",
    "attach_verifier_disagreement",
    "attribute_route_cost",
    "build_abandoned_route_outcome",
    "build_benchmark_conclusion",
    "build_benchmark_conclusion_verification",
    "build_guarded_canary_route_outcome",
    "build_qualified_human_approval_disposition",
    "build_qualified_human_approval_request",
    "build_qualified_human_authority_grant",
    "build_shadow_evaluation_input",
    "build_shadow_recommendation_verification",
    "evaluate_benchmark",
    "evaluate_controlled_replay",
    "evaluate_live_scope_candidate",
    "evaluate_qualified_human_finalization",
    "evaluate_shadow_routes",
    "execute_anthropic_canary_once",
    "execute_benchmark_verifier_panel",
    "execute_gemini_canary_once",
    "execute_guarded_canary",
    "execute_live_verification",
    "execute_live_verification_with_evidence",
    "execute_openai_canary_once",
    "execute_provider_once",
    "execute_with_transient_retry",
    "load_benchmark_fixtures",
    "load_pricing_evidence",
    "load_route_outcomes",
    "run_controlled_replay",
    "run_staged_documentation_replay",
    "verify_guarded_canary_outcome",
    "verify_guarded_canary_outcome_with_evidence",
]
