from pathlib import Path

def r(path, old, new):
    p=Path(path); t=p.read_text()
    if t.count(old)!=1: raise SystemExit(f'{path}: expected 1 match, got {t.count(old)}')
    p.write_text(t.replace(old,new))

r('policy/routing/routing.yaml', '''    fallback:\n      agent: agy\n      model: gemini-3.1-pro-preview\n      profile: sol\n      reasoning: medium\n\n    review_when:\n''', '''    fallback:\n      agent: agy\n      model: gemini-3.6-flash\n      profile: terra\n      reasoning: medium\n      purpose: stable cross-provider coding fallback without preview acceptance\n\n    review_when:\n''')

r('policy/routing/routing.yaml', '''  high_volume_simple:\n    primary:\n      agent: claude\n      model: claude-haiku-4-5\n      profile: luna\n      reasoning: low\n    fallback:\n      agent: agy\n      model: gemini-3.6-flash\n      profile: luna\n      reasoning: low\n      purpose: continue high-volume work when the Anthropic route is unavailable\n    alternatives:\n      - agent: agy\n        model: gemini-3.6-flash\n        profile: luna\n      - agent: codex\n        model: gpt-5.6-luna\n        profile: luna\n    verifier:\n      agent: agy\n      model: gemini-3.6-flash\n      profile: luna\n      reasoning: medium\n      purpose: provider-diverse pointwise validation of bounded high-volume output\n    semantic_reviewer:\n      agent: claude\n      model: claude-sonnet-5\n      profile: sol\n      reasoning: medium\n      purpose: fresh semantic verification when Gemini becomes the model-fallback executor\n    technical_verifier:\n      agent: codex\n      model: gpt-5.6-sol\n      profile: sol\n      reasoning: medium\n      purpose: fresh provider-diverse verification when Anthropic is unavailable\n''', '''  high_volume_simple:\n    primary:\n      agent: agy\n      model: gemini-3.5-flash-lite\n      profile: luna\n      reasoning: low\n      purpose: stable low-cost high-throughput execution\n    fallback:\n      agent: claude\n      model: claude-haiku-4-5\n      profile: luna\n      reasoning: low\n      purpose: cross-provider bounded language throughput when Google is unavailable\n    alternatives:\n      - agent: codex\n        model: gpt-5.6-luna\n        profile: luna\n      - agent: agy\n        model: gemini-3.6-flash\n        profile: luna\n    verifier:\n      agent: claude\n      model: claude-haiku-4-5\n      profile: luna\n      reasoning: default\n      purpose: provider-diverse pointwise validation of the primary Flash-Lite route\n    semantic_reviewer:\n      agent: agy\n      model: gemini-3.6-flash\n      profile: luna\n      reasoning: medium\n      purpose: fresh verification when Haiku becomes fallback executor and Google remains eligible\n    technical_verifier:\n      agent: codex\n      model: gpt-5.6-sol\n      profile: sol\n      reasoning: medium\n      purpose: fresh provider-diverse verification when Google is unavailable or stronger review is required\n''')

r('policy/routing/routing.yaml', '''  throughput:\n    - agent: agy\n      model: gemini-3.6-flash\n    - agent: codex\n      model: gpt-5.6-luna\n    - agent: claude\n      model: claude-haiku-4-5\n''', '''  throughput:\n    - agent: agy\n      model: gemini-3.5-flash-lite\n    - agent: claude\n      model: claude-haiku-4-5\n    - agent: codex\n      model: gpt-5.6-luna\n    - agent: agy\n      model: gemini-3.6-flash\n''')

r('policy/routing/specialist-model-routing.yaml', '''  luna_throughput:\n    primary:\n      agent: codex\n      model: gpt-5.6-luna\n      reasoning_by_risk:\n        low: low\n        medium: medium\n        high: high\n        critical: high\n    fallback:\n      agent: claude\n      model: claude-haiku-4-5\n      reasoning: default\n    verifier:\n      agent: agy\n      model: gemini-3.6-flash\n''', '''  luna_throughput:\n    primary:\n      agent: agy\n      model: gemini-3.5-flash-lite\n      reasoning_by_risk:\n        low: low\n        medium: medium\n        high: high\n        critical: high\n    fallback:\n      agent: claude\n      model: claude-haiku-4-5\n      reasoning: default\n    verifier:\n      agent: codex\n      model: gpt-5.6-luna\n''')

r('policy/routing/specialist-model-routing.yaml', '''    conditional_effort_escalation:\n      model: claude-opus-5\n      reasoning: max\n      use_when:\n      - unresolved_material_disagreement\n      - critical_cross_system_ambiguity\n      - quality_gain_is_decision_relevant\n''', '''    conditional_effort_escalation:\n      model: claude-fable-5\n      reasoning: max\n      use_when:\n      - unresolved_material_disagreement_after_opus_review\n      - critical_cross_system_ambiguity_after_standard_escalation\n      - long_horizon_agentic_reasoning_where_quality_gain_is_decision_relevant\n''')

r('policy/routing/mission-control-routing.yaml', '''        - authority_violation\n        - unresolved_pipeline_loop\n''', '''        - authority_violation\n    frontier_escalation:\n      agent: claude\n      model: claude-fable-5\n      profile: sol\n      reasoning: max\n      use_when:\n        - unresolved_pipeline_loop_after_opus_review\n        - long_horizon_agentic_orchestration_remains_inconclusive\n        - cross_system_authority_conflict_remains_unresolved\n''')

p=Path('models.yaml'); t=p.read_text()
marker='''    limitations:\n      - escalate consequential synthesis to a stronger reasoning model\n\n'''
addition='''  gemini-flash-lite:\n    provider_family: google\n    concrete_model: gemini-3.5-flash-lite\n    availability: stable\n    role: primary economical high-volume execution\n    profile: luna\n    preferred_for: [extraction, classification, structured_transformation, document_parsing, simple_high_volume_work]\n    limitations:\n      - escalate ambiguity and consequential synthesis to a stronger reasoning route\n      - preserve provider-diverse verification\n\n'''
idx=t.index(marker,t.index('  gemini-flash:'))+len(marker); t=t[:idx]+addition+t[idx:]
t=t.replace('role: candidate maximum-capability escalation\n    routing_status: registered_unrouted','role: narrow maximum-capability frontier escalation\n    routing_status: routed_frontier_escalation')
p.write_text(t)

r('registry/models/models.yaml', '''    teo_routing_role: candidate critical escalation implementation\n    routing_status: registered_unrouted\n    routing_status_reason: retained for evidence-based escalation evaluation; not promoted by release recency alone\n''', '''    teo_routing_role: narrow frontier escalation after established high-consequence routes remain inconclusive\n    routing_status: routed_frontier_escalation\n    routing_status_reason: only for unresolved long-horizon or cross-system escalation where added capability justifies cost and latency\n''')
r('registry/models/models.yaml', '''    teo_routing_role: candidate economical throughput implementation\n    routing_status: registered_unrouted\n    routing_status_reason: evaluate against current Luna and Flash throughput routes before adoption\n    evidence_type: provider_claim\n''', '''    teo_routing_role: primary economical throughput implementation\n    routing_status: routed\n    input_modalities: [text, image, video, audio, pdf]\n    output_modalities: [text]\n    reasoning_control: thinking_level\n    reasoning_levels: [minimal, low, medium, high]\n    reasoning_default: minimal\n    context_window_tokens: 1048576\n    max_output_tokens: 65536\n    evidence_type: provider_claim\n''')

p=Path('README.md'); t=p.read_text()
for old,new in {
'Gemini 3.1 Pro Preview as cross-provider fallback where explicitly accepted':'stable Gemini 3.6 Flash as routine cross-provider coding fallback',
'**Claude Haiku 4.5** on the current reference route | Gemini 3.6 Flash routine fallback; GPT-5.6 Luna registered alternative; Claude Sonnet 5 escalation when ambiguity exceeds throughput scope':'**Gemini 3.5 Flash-Lite** | Claude Haiku 4.5 cross-provider fallback; GPT-5.6 Luna independent alternative; Gemini 3.6 Flash for stronger bounded agentic or multimodal work',
'**Claude Fable 5** is registered as a frontier-capability candidate.':'**Claude Fable 5** is routed only as a narrow frontier escalation after established Opus/Sol paths remain inconclusive.',
'**Gemini 3.5 Flash-Lite** is registered as a throughput candidate.':'**Gemini 3.5 Flash-Lite** is the primary economical bounded-throughput implementation.'
}.items():
    if old not in t: raise SystemExit(f'README missing: {old}')
    t=t.replace(old,new)
p.write_text(t)
print('applied')
